import type { Metadata } from "next";
import { Inter, Italiana } from "next/font/google";
import "./globals.css";
import { theme } from "../app/theme/theme";
import { ThemeProvider, CssBaseline } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

const italiana = Italiana({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-italiana",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <body
          className={`${italiana.variable} ${inter.className} bg-green inline text-black`}
        >
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
