import Head from "next/head";
import type { Metadata } from "next";
import { Inter, Italiana } from "next/font/google";
import "@/public/globals.css";

const inter = Inter({ subsets: ["latin"] });

const italiana = Italiana({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-italiana",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Italiana:wght@400&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={`${italiana.variable} ${inter.className} bg-night min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
